version 2

diff --git a/latig0sx.app/Contents/Resources/latigo-check b/latig0sx.app/Contents/Resources/latigo-check
--- a/latig0sx.app/Contents/Resources/latigo-check
+++ b/latig0sx.app/Contents/Resources/latigo-check
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-# Copyright (c) 2012/2015 lain <lain@braincakes.org>
+# Copyright (c) 2014/2016 lain <lain@braincakes.org>
 # All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
@@ -38,12 +38,19 @@ read user
 
 clear
 
-echo -------------------------------------------
-echo " Latigo - OS X Auditing                  "
-echo "     by lain                             "
-echo -------------------------------------------
+echo ---------------------------------------
+echo "   Latig0sx v2.0 - OS X Auditing     "
+echo "       by lain                       "
+echo ---------------------------------------
 
-inuser=$user
+inuser=$user 
+
+## Check if user input exists
+if [ ! -d /Users/$inuser ] 
+then
+	echo "\n Error - User $inuser doesn't exist. Enter a valid user.\n "
+	exit 1
+fi
 
 ## Configuration Overview ##
 echo "\n[[Configuration Overview]]"
@@ -168,28 +175,48 @@ for u in $users
 do
 	blimit=$(quota -v $u | grep / | awk '{ print $4 }')
 	inodelimit=$(quota -v $u | grep / | awk '{ print $7 }')  
-    if [ -z $blimit ]
-    then
-        blimit=0
-    fi
-    if [ -z $inodelimit ]
-    then
-        inodelimit=0
-    fi
+        if [ -z $blimit ]
+        then
+        	blimit=0
+        fi
+        if [ -z $inodelimit ]
+        then
+                inodelimit=0
+        fi
 	echo "\t \t User: $u - Block limit: $blimit - File limit: $inodelimit"
 	if [ $blimit -eq 0 ] && [ $inodelimit -eq 0 ]
 	then
 		echo "\t \t Must set disk quota for user $u [ \033[00;31mWarning\033[0m ]"
 	fi
 	if [ $blimit -eq 0 ] && [ $inodelimit -ne 0 ]
-    then
-        echo "\t \t Must set Block limit for user $u [ \033[00;31mWarning\033[0m ]"
-    fi
-    if [ $blimit -ne 0 ] && [ $inodelimit -eq 0 ]
-    then
-        echo "\t \t Must set File limit for user $u [ \033[00;31mWarning\033[0m ]"
-    fi
+        then
+                echo "\t \t Must set Block limit for user $u [ \033[00;31mWarning\033[0m ]"
+        fi 
+        if [ $blimit -ne 0 ] && [ $inodelimit -eq 0 ]
+        then
+                echo "\t \t Must set File limit for user $u [ \033[00;31mWarning\033[0m ]"
+        fi
 done
+
+# Checking the sudo timeout period
+echo "\t [Checking sudo timeout period]"
+stimep=$(sudo cat /etc/sudoers | grep timestamp | awk '{ print $2 $3 $4 $5}')
+if [ ! -z $stimep ]
+then
+        echo "\t \t Sudo timeout period is set to $stimep"
+else
+	echo "\t \t No sudo timeout period setting [ \033[00;31mWarning\033[0m ]"
+fi 
+
+# Checking core dumps
+echo "\t [Checking core dumps]"
+cdump=$(launchctl limit core | awk '{ print $3 }')
+if [ $cdump == "0" ]
+then
+        echo "\t \t Core dumps disabled"
+else
+        echo "\t \t Core dumps enabled: $cdump [ \033[00;31mWarning\033[0m ]"
+fi
 
 ## Checking Global System Settings ##
 echo "\n[[Checking Global System Settings]]"
@@ -254,12 +281,12 @@ if [ "$(echo $secaudit)" ]
 then
         if [ "$(echo $secaudit | awk ' { print $1 } ')" == "-" ]
         then 
-            echo "\t \t Security Audit daemon loaded but not running [ \033[00;31mWarning\033[0m ]"
+                echo "\t \t Security Audit daemon loaded but not running [ \033[00;31mWarning\033[0m ]"
         else
-            echo "\t \t Security Audit daemon is running"
+                echo "\t \t Security Audit daemon is running"
         fi
 else
-    echo "\t \t Security Audit daemon unloaded [ \033[00;31mWarning\033[0m ]"
+        echo "\t \t Security Audit daemon unloaded [ \033[00;31mWarning\033[0m ]"
 fi
 
 ## Checking System Preferences ##
@@ -267,22 +294,31 @@ echo "\n[[Checking System Preferences]]"
 	
 # Checking MobileMe Preferences
 echo "\t [Checking MobileMe Preferences]"
+mobileme=$(defaults read ~/Library/Preferences/.GlobalPreferences iToolsMember 2>&1)
+if [ "$(echo $mobileme | awk '/does not exist/')" ]
+then
+	echo "\t \t MobileMe Preferences disabled"
+else
+	echo "\t \t MobileMe Preferences enabled [ \033[00;31mWarning\033[0m ]"
+fi
+
 # Checking Disable Sync options
+echo "\t [Checking Sync optins disabled]"
 syncopts=$(defaults read /Library/Preferences/com.apple.DotMacSync ShouldSyncWithServer 2>&1)
 if [ "$(echo $syncopts | awk '/does not exist/')" ]
 then
-    echo "\t \t Sync options not installed"
+        echo "\t \t Sync options not installed"
 else
 	if [ $syncopts -eq -1 ]
-    then
+        then
 		echo "\t \t Sync options disabled"
 	else
 		echo "\t \t Sync options enabled [ \033[00;31mWarning\033[0m ]"
 		#Checking Disable iDisk Syncing
-        echo "\t \t [Checking Disable iDisk Syncing]"
-        echo "\t \t Enter your MobileMe user name:"
-        read mirroruser
-        idisksync=$(defaults -currentHost read com.apple.idisk $mirroruser 2>&1)
+                echo "\t \t [Checking Disable iDisk Syncing]"
+                echo "\t \t Enter your MobileMe user name:"
+                read mirroruser
+                idisksync=$(defaults -currentHost read com.apple.idisk $mirroruser 2>&1)
 		if [ "$(echo $idisksync | awk '/does not exist/')" ]
 		then
 			echo "\t \t iDisk Syncing not installed"
@@ -294,7 +330,7 @@ else
 				echo "\t \t iDisk Syncing disabled"
 			fi
 		fi
-    fi
+        fi
 fi
 
 # Checking Accounts Preferences
@@ -341,6 +377,20 @@ else
 		echo "\t \t Show Restart, Sleep and ShutDown Buttons disabled"
 	fi
 fi
+
+# Checking Allow guests to connect to shared folders
+guestshare=$(defaults read /Library/Preferences/com.apple.AppleFileServer guestAccess 2>&1)
+if [ "$(echo $guestshare | awk '/does not exist/')" ]
+then
+        echo "\t \t Allow guests to connect to shared folders not installed"
+else
+        if [ $guestshare -eq 0 ]
+        then
+                echo "\t \t Allow guests to connect to shared folders disabled"
+        else
+                echo "\t \t Allow guests to connect to shared folders enabled [ \033[00;31mWarning\033[0m ]"
+        fi
+fi
  
 # Checking fast user switching disabled
 fastUserSwitching=$(defaults read /Library/Preferences/.GlobalPreferences MultipleSessionEnabled 2>&1)
@@ -386,6 +436,20 @@ else
 	fi
 fi
 
+# Checking Bluetooth internet connection sharing
+blueshare=$(defaults read /Library/Preferences/com.apple.Bluetooth PANServices 2>&1)
+if [ "$(echo $blueshare | awk '/does not exist/')" ]
+then
+        echo "\t \t Bluetooth internet connection sharing not installed"
+else
+	if [ $blueshare -eq 0 ]
+        then
+                echo "\t \t Bluetooth internet connection sharing is disabled"
+        else
+                echo "\t \t Bluetooth internet connection sharing is enabled [ \033[00;31mWarning\033[0m ]"
+        fi
+fi
+
 # Checking CDs & DVDs Preferences 
 echo "\t [Checking CDs & DVDs Preferences]"
 
@@ -425,9 +489,9 @@ then
 else
 	if [ "$(echo $cdPrefPicture | grep "action = 1")" ]
 	then
-        echo "\t \t Picture CD automatic action disabled"
+        	echo "\t \t Picture CD automatic action disabled"
 	else
-        echo "\t \t Picture CD automatic action enabled [ \033[00;31mWarning\033[0m ]"
+        	echo "\t \t Picture CD automatic action enabled [ \033[00;31mWarning\033[0m ]"
 	fi
 fi
 
@@ -435,13 +499,13 @@ fi
 dvdPrefBlank=$(defaults read /Users/$inuser/Library/Preferences/com.apple.digihub com.apple.digihub.blank.dvd.appeared action 2>&1)
 if [ "$(echo $dvdPrefBlank | awk '/does not exist/')" ]
 then
-    echo "\t \t Blank CD automatic action not defined"
+        echo "\t \t Blank CD automatic action not defined"
 else
 	if [ "$(echo $dvdPrefBlank | grep "action = 1")" ]
 	then
-        echo "\t \t Blank DVD automatic action disabled"
+        	echo "\t \t Blank DVD automatic action disabled"
 	else
-        echo "\t \t Blank DVD automatic action enabled [ \033[00;31mWarning\033[0m ]"
+        	echo "\t \t Blank DVD automatic action enabled [ \033[00;31mWarning\033[0m ]"
 	fi
 fi
 
@@ -449,12 +513,12 @@ fi
 dvdPrefVideo=$(defaults read /Users/$inuser/Library/Preferences/com.apple.digihub com.apple.digihub.dvd.video.appeared action 2>&1)
 if [ "$(echo $cdPrefVideo | awk '/does not exist/')" ]
 then
-    echo "\t \t Video CD automatic action not defined"
-    if [ "$(echo $dvdPrefVideo | grep "action = 1")" ]
+        echo "\t \t Video CD automatic action not defined"
+	if [ "$(echo $dvdPrefVideo | grep "action = 1")" ]
 	then 
-        echo "\t \t Video DVD automatic action disabled"
+        	echo "\t \t Video DVD automatic action disabled"
 	else
-        echo "\t \t Video DVD automatic action enabled [ \033[00;31mWarning\033[0m ]"
+        	echo "\t \t Video DVD automatic action enabled [ \033[00;31mWarning\033[0m ]"
 	fi
 fi
 
@@ -499,7 +563,12 @@ if [ "$(echo $idleTimeScreenSaver | awk '/does not exist/')" ]
 then
 	echo "\t \t Idle time for screen saver not setting [ \033[00;31mWarning\033[0m ]"
 else
-	echo "\t \t Idle time for screen saver setting"
+	if [ $idleTime -lt 900 ]
+	then
+		echo "\t \t Idle time for screen saver is setting to $idleTime"
+	else
+		echo "\t \t Idle time for screen saver is not set to a value lower than 900  [ \033[00;31mWarning\033[0m ]"
+        fi
 fi
 
 # Set host corner to activate screen saver
@@ -509,11 +578,11 @@ then
 	echo "\t \t Host corner to activate screen saver not setting"
 else    
 	if [ $hostcornerScreenSave -eq 5 ]
-    then
-        echo "\t \t Host corner to activate screen saver setting and value 5"
-    else
-        echo "\t \t Host corner to activate screen saver setting but not value 5[ \033[00;31mWarning\033[0m ]"
-    fi
+    	then
+        	echo "\t \t Host corner to activate screen saver setting and value 5"
+    	else
+        	echo "\t \t Host corner to activate screen saver setting but not value 5[ \033[00;31mWarning\033[0m ]"
+    	fi
 fi
 
 # Set modifier key to 0 wvous-corner_code-modifier 
@@ -522,12 +591,12 @@ if [ "$(echo $modifierKey | awk '/does not exist/')" ]
 then 
 	echo "\t \t Modifier key to 0 wvous-corner_code-modifier not setting [ \033[00;31mWarning\033[0m ]"
 else
-    if [ $modifierKey -eq 0 ]
-    then
-        echo "\t \t Modifier key to 0 wvous-corner_code-modifier setting"
-    else
-        echo "\t \t Modifier key wvous-corner_code-modifier must be setting 0 [ \033[00;31mWarning\033[0m ]"
-    fi
+    	if [ $modifierKey -eq 0 ]
+    	then
+        	echo "\t \t Modifier key to 0 wvous-corner_code-modifier setting"
+    	else
+        	echo "\t \t Modifier key wvous-corner_code-modifier must be setting 0 [ \033[00;31mWarning\033[0m ]"
+    	fi
 fi
 
 # Automatically hide and show Dock
@@ -536,12 +605,12 @@ if [ "$(echo $autoDock | awk '/does not exist/')" ]
 then 
 	echo "\t \t Automatically hide and show Dock not setting"
 else 
-    if [ "$autoDock" == "YES" ]
-    then
-        echo "\t \t Automatically hide and show Dock setting"
-    else
-        echo "\t \t Automatically hide and show Dock not setting [ \033[00;31mWarning\033[0m ]"
-    fi
+    	if [ "$autoDock" == "YES" ]
+    	then
+        	echo "\t \t Automatically hide and show Dock setting"
+    	else
+        	echo "\t \t Automatically hide and show Dock not setting [ \033[00;31mWarning\033[0m ]"
+    	fi
 fi
 
 # Checking Computer Sleep disabled
@@ -592,9 +661,9 @@ if [ "$(echo $restartAuto)" ]
 then
 	if [ $restartAuto -eq 0 ]
 	then
-        echo "\t \t Restart automatically after power failure disabled"
+        	echo "\t \t Restart automatically after power failure disabled"
 	else
-        echo "\t \t Restart automatically after power failure enabled [ \033[00;31mWarning\033[0m ]"
+        	echo "\t \t Restart automatically after power failure enabled [ \033[00;31mWarning\033[0m ]"
 	fi
 else
 	echo "\t \t Restart automatically after power failure not setting"
@@ -648,11 +717,11 @@ askForPassword=$(defaults read /Users/$inuser/Library/Preferences/com.apple.scre
 if [ -z "$(echo $askForPassword | awk '/does not exist/')" ]
 then
 	if [ $askForPassword -eq 1 ]
-    then
-        echo "\t \t Require password to wake this computer from sleep or screen saver enabled"
-    else
-        echo "\t \t Require password to wake this computer from sleep or screen saver disabled [ \033[00;31mWarning\033[0m ]"
-    fi
+    	then 
+        	echo "\t \t Require password to wake this computer from sleep or screen saver enabled"
+    	else
+        	echo "\t \t Require password to wake this computer from sleep or screen saver disabled [ \033[00;31mWarning\033[0m ]"
+    	fi
 else
 	echo "\t \t Require password to wake this computer from sleep or screen saver not setting [ \033[00;31mWarning\033[0m ]"
 fi
@@ -730,7 +799,7 @@ else
 	if [ "$(echo $fwverb)" == 1 ]
 	then	
 		echo "\t \t Firewall (IPFW) logging is enabled"
-        echo "\t \t Recomendation: set verbose to value 2 [ \033[00;31mWarning\033[0m ]"
+        	echo "\t \t Recomendation: set verbose to value 2 [ \033[00;31mWarning\033[0m ]"	
 	else
 		echo "\t \t Firewall (IPFW) logging is disabled [ \033[00;31mWarning\033[0m ]"
 	fi
@@ -743,7 +812,7 @@ then
 	echo "\t \t Firewall Logging not setting [ \033[00;31mWarning\033[0m ]"
 else
 	if [ $appfwverb == 1 ]
-    then
+        then
 		echo "\t \t Application Firewall Logging Enabled"
 	else
 		echo "\t \t Application Firewall Logging Disabled [ \033[00;31mWarning\033[0m ]"
@@ -757,9 +826,9 @@ then
 	echo "\t \t Secure virtual memory not setting [ \033[00;31mWarning\033[0m ]"
 else
 	if [ $secureVirtualMemory == "YES" ]
-    then
+    	then
 		echo "\t \t Secure virtual memory enabled"
-    else
+    	else
 		echo "\t \t Secure virtual memory disabled [ \033[00;31mWarning\033[0m ]"
 	fi
 fi
@@ -787,10 +856,10 @@ then
 	echo "\t \t Speed Recognition not setting"
 else
 	if [ $speedRecognition == "false" ]
-    then
-        echo "\t \t Speed Recognition disabled"
-    else
-        echo "\t \t Speed Recognition enabled [ \033[00;31mWarning\033[0m ]"
+    	then
+        	echo "\t \t Speed Recognition disabled"
+    	else
+        	echo "\t \t Speed Recognition enabled [ \033[00;31mWarning\033[0m ]"
    	fi
 fi
 
@@ -800,7 +869,7 @@ if [ "$(echo $talkingAlertsSpeak | awk '/does not exist/')" ]
 then
 	echo "\t \t Text to Speech settings not setting"
 else 
-    if [ $talkingAlertsSpeak == "false" ]
+    	if [ $talkingAlertsSpeak == "false" ]
 	then
 		echo "\t \t Text to Speech settings disabled"
 	else
@@ -1062,6 +1131,8 @@ services=(
 # If a VPN is not used, disable the IKE VPN key management service
 com.apple.racoon
 # Disable Bonjour!!!
+com.apple.mDNSResponder
+com.apple.mDNSResponderHelper
 # Disable DVD or CD Sharing
 com.apple.ODSAgent
 # Disable FTP
@@ -1074,6 +1145,7 @@ com.apple.smb.sharepoints
 com.apple.smbfs_load_kext
 org.samba.winbindd
 # Disable AFP
+com.apple.AppleFileServer
 com.apple.afpfs_afpLoad
 com.apple.afpfs_checkafp
 # Disable NFS
@@ -1095,7 +1167,7 @@ com.apple.eppc
 com.apple.xgridagentd
 com.apple.xgridcontrollerd
 # Disable Internet Sharing
-com.apple.InternetSharin
+com.apple.InternetSharing
 # Turn off AirPort Services using the following commands
 com.apple.airportPrefsUpdater
 com.apple.AirPort.wps
@@ -1117,7 +1189,8 @@ com.apple.blued
 com.apple.IIDCAssistant
 com.apple.UserNotificationCenter
 com.apple.webdavfs_load_kext
-org.postfix.master )
+org.postfix.master
+eppc )
 for s in ${services[@]} 
 do
 	(launchctl list | grep "$s" 1>/dev/null) && echo "\t \t Service $s must be unloaded [ \033[00;31mWarning\033[0m ]"
diff --git a/latig0sx.app/Contents/Resources/latigo-hardening b/latig0sx.app/Contents/Resources/latigo-hardening
--- a/latig0sx.app/Contents/Resources/latigo-hardening
+++ b/latig0sx.app/Contents/Resources/latigo-hardening
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-# Copyright (c) 2012/2015 lain <lain@braincakes.org>
+# Copyright (c) 2014/2016 lain <lain@braincakes.org>
 # All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
@@ -27,7 +27,7 @@
 
 clear
 
-echo "Latig0sx needs to be started with administrator priviledges, please authenticate first:"
+echo "Latig0sx needs to be started with administrator priviledges, please authenticate first: "
 
 sudo wait
 
@@ -38,12 +38,19 @@ read user
 
 clear
 
-echo -------------------------------------------
-echo " Latigo - OS X Hardening                 "
-echo "     by lain                             "
-echo -------------------------------------------
+echo --------------------------------------
+echo "   Latig0sx v2.0 - OS X Hardening     "
+echo "       by lain                        "
+echo --------------------------------------
 
 inuser=$user
+
+## Check if user input exists
+if [ ! -d /Users/$inuser ]
+then
+        echo "\nError - User $inuser doesn't exist. Enter a valid user\n "
+        exit 1
+fi
 
 echo "\n[[Configuration Overview]]"
 
@@ -56,32 +63,32 @@ then
 	if [ -n $secoption ] && [ $secoption == "0" ]
 	then
 		sudo sysctl -w kern.securelevel=0 | 2>&1 | 1>/dev/null
-		echo "\t \t\033[00;32mDone\033[0m - kern.securelevel set to $secoption"
+		echo "\t \t\033[00;32mDone\033[0m - kern.securelevel sets to $secoption"
 	fi
 	if [ -z $secoption ] || [ $secoption == "1" ]
-    then
-        sudo sysctl -w kern.securelevel=1 | 2>&1 | 1>/dev/null
-        echo "\t \t\033[00;32mDone\033[0m - kern.securelevel set to $secoption"
-    fi
+        then
+                sudo sysctl -w kern.securelevel=1 | 2>&1 | 1>/dev/null
+                echo "\t \t\033[00;32mDone\033[0m - kern.securelevel sets to $secoption"
+        fi
 	if [ -n $secoption ] && [ $secoption == "2" ]
-    then
-        sudo sysctl -w kern.securelevel=2 | 2>&1 | 1>/dev/null
-        echo "\t \t\033[00;32mDone\033[0m - kern.securelevel set to $secoption"
-    fi
-    if [ -n $secoption ] && [ $secoption == "3" ]
-    then
-        sudo sysctl -w kern.securelevel=3 | 2>&1 | 1>/dev/null
-        echo "\t \t\033[00;32mDone\033[0m - kern.securelevel set to $secoption"
-    fi
+        then
+                sudo sysctl -w kern.securelevel=2 | 2>&1 | 1>/dev/null
+                echo "\t \t\033[00;32mDone\033[0m - kern.securelevel sets to $secoption"
+        fi
+        if [ -n $secoption ] && [ $secoption == "3" ]
+        then
+                sudo sysctl -w kern.securelevel=3 | 2>&1 | 1>/dev/null
+                echo "\t \t\033[00;32mDone\033[0m - kern.securelevel sets to $secoption"
+        fi
 fi
 
 printf "\tCreate daemon for downloading and installing the latest Software Updates [y/n] (y) ? "
 read softupdate
 if [ -z $softupdate ] || [ $softupdate == "y" ]
 then
-	if [ -f conf/com.softwareupdate.plist ]
+	if [ -f ../conf/com.softwareupdate.plist ]
 	then
-		cp conf/com.softwareupdate.plist /System/Library/LaunchDaemons/
+		sudo cp conf/com.softwareupdate.plist /System/Library/LaunchDaemons/
 		chown root:wheel /System/Library/LaunchDaemons/com.softwareupdate.plist
 		launchctl load -w /System/Library/LaunchDaemons/com.softwareupdate.plist > /dev/null 2>&1
 		echo "\t \t\033[00;32mDone\033[0m - com.softwareupdate.plist daemon loaded" 
@@ -97,10 +104,43 @@ read diskquota
 if [ -z $diskquota ] || [ $diskquota == "y" ]
 then
 	sudo touch /.quota.ops.user
-	sudo touch /.quota.ops.group
-	sudo quotaon -a
-	sudo edquota $inuser
+	touch /.quota.ops.group
+	quotaon -a
+	edquota $inuser
 	echo "\t \t\033[00;32mDone\033[0m - Disk Quotas enabled"
+fi
+
+printf "\tCreate an access warning for the login window [y/n] (y) ? "
+read warnloginwin
+if [ -z $warnloginwin ] || [ $warnloginwin == "y" ]
+then
+	printf "\t \tEnter access warning message: "
+        read warnmsg
+        sudo defaults write /Library/Preferences/com.apple.loginwindow LoginwindowText $warnmsg
+	echo "\t \t\033[00;32mDone\033[0m - Access warning message created"
+fi
+
+printf "\tReduce the sudo timeout period [y/n] (y) ? "
+read sudotimeout
+if [ -z $sudotimeout ] || [ $sudotimeout == "y" ]
+then
+        if [ "$(grep "^timestamp_timeout" /etc/sudoers)" ]
+        then
+                sudo sed 's/^timestamp_timeout*$/Defaults timestamp_timeout=0/g' /etc/sudoers > /etc/sudoers.tmp
+                cp /etc/sudoers.tmp /etc/sudoers
+                rm /etc/sudoers.tmp
+        else
+                sudo echo "Defaults timestamp_timeout=0" >> /etc/sudoers
+        fi
+	echo "\t \t\033[00;32mDone\033[0m - sudo timeout period reduced"
+fi
+
+printf "\tDisable core dumps [y/n] (y) ? "
+read cdump
+if [ -z $cdump ] || [ $cdump == "y" ]
+then
+	sudo launchctl limit core 0
+        echo "\t \t\033[00;32mDone\033[0m - sudo timeout period reduced"
 fi
 
 echo "\n[[Global System Settings]]"
@@ -123,14 +163,14 @@ then
 		if [ -z "$(grep "^AUDIT=-YES-" /etc/hostconfig)" ]
 		then
 			sed 's/^AUDIT.*$/AUDIT=-YES-/g' /etc/hostconfig > /etc/hostconfig.tmp
-			cp /etc/hostconfig.tmp /etc/hostconfig
+			sudo cp /etc/hostconfig.tmp /etc/hostconfig
 			rm /etc/hostconfig.tmp
 		fi
 	else
-		echo AUDIT=-YES- >> /etc/hostconfig
+		sudo echo AUDIT=-YES- >> /etc/hostconfig
 	fi
 	echo "\t \t\033[00;32mDone\033[0m - AUDIT=-YES in /etc/hostconfig"
-	launchctl load -w /System/Library/LaunchDaemons/com.apple.auditd.plist > /dev/null 2>&1
+	sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.auditd.plist > /dev/null 2>&1
 	echo "\t \t\033[00;32mDone\033[0m - com.apple.auditd loaded"
 	launchctl start com.apple.auditd
 	echo "\t \t\033[00;32mDone\033[0m - com.apple.auditd started"
@@ -154,15 +194,36 @@ printf "\tDisable Bluetooth Controller [y/n] (y) ? "
 read blcontr
 if [ -z $blcontr ] || [ $blcontr == "y" ]
 then
-	defaults write /Library/Preferences/com.apple.Bluetooth/ControllerPowerState -int 0 2>/dev/null
+	sudo defaults write /Library/Preferences/com.apple.Bluetooth ControllerPowerState -int 0 2>/dev/null
+        launchctl unload -w /System/Library/LaunchDaemons/com.apple.blued.plist 2>/dev/null
+	killall -HUP blued 2>/dev/null
 	echo "\t \t\033[00;32mDone\033[0m - Bluetooth Controller disabled"
+fi
+
+printf "\tRemove Bluetooth Hardware [y/n] (y) ? "
+read blthw
+if [ -z $blthw ] || [ $blthw == "y" ]
+then
+        sudo rm -rf /System/Library/Extensions/IOBluetoothFamily.kext
+        rm -rf /System/Library/Extensions/IOBluetoothHIDDriver.kext
+        launchctl unload -w /System/Library/LaunchDaemons/com.apple.blued.plist 2>/dev/null
+        echo "\t \t\033[00;32mDone\033[0m - Bluetooth Hardware removed (reboot the Mac)"
+fi
+
+printf "\tDisable Bluetooth internet connection sharing [y/n] (y) ? "
+read bltshare
+if [ -z $bltshare ] || [ $bltshare == "y" ]
+then
+        sudo defaults write /Library/Preferences/com.apple.Bluetooth PANServices -int 0 2>/dev/null
+	killall -HUP blued 2>/dev/null
+        echo "\t \t\033[00;32mDone\033[0m - Bluetooth internet connection sharing disabled"
 fi
 
 printf "\tDisable IR remote control [y/n] (y) ? "
 read irremcontr
 if [ -z $irremcontr ] || [ $irremcontr == "y" ]
 then
-	defaults write /Library/Preferences/com.apple.driver.AppleIRController DeviceEnabled -bool no
+	sudo defaults write /Library/Preferences/com.apple.driver.AppleIRController DeviceEnabled -bool no
 	echo "\t \t\033[00;32mDone\033[0m - IR remote control disabled"
 fi
 
@@ -170,7 +231,7 @@ printf "\tDisable internal microphone or line-in [y/n] (y) ? "
 read microph
 if [ -z $microph ] || [ $microph == "y" ]
 then
-	osascript -e "set volume input volume 0"
+	sudo osascript -e "set volume input volume 0"
 	echo "\t \t\033[00;32mDone\033[0m - internal microphone disabled"
 fi
 
@@ -178,7 +239,7 @@ printf "\tEnable Application Firewall Logging [y/n] (y) ? "
 read apfwlog
 if [ -z $apfwlog ] || [ $apfwlog == "y" ]
 then
-	defaults write /Library/Preferences/com.apple.alf loggingenabled 1
+	sudo defaults write /Library/Preferences/com.apple.alf loggingenabled 1
 	echo "\t \t\033[00;32mDone\033[0m - Application firewall logging enabled"
 fi
 
@@ -196,7 +257,7 @@ printf "\tDisable root account [y/n] (y) ? "
 read disroot
 if [ -z $disroot ] || [ $disroot == "y" ]
 then 
-	dsenableroot -d
+	sudo dsenableroot -d
 	echo "\t \t\033[00;32mDone\033[0m - root account disabled"
 fi
 
@@ -208,12 +269,46 @@ then
 	echo "\t \t\033[00;32mDone\033[0m - $inuser home folder permissions set to go-rx"
 fi
 
+printf "\tDisplay login window as name and password [y/n] (y) ? "
+read displaylogin
+if [ -z $displaylogin ] || [ $displaylogin == "y" ]
+then
+	sudo defaults write /Library/Preferences/com.apple.loginwindow SHOWFULLNAME -bool yes
+	echo "\t \t\033[00;32mDone\033[0m - Display login window as name and password"
+fi
+
+printf "\tDisable Show password hints [y/n] (y) ? "
+read passhints
+if [ -z $passhints ] || [ $passhints == "y" ]
+then
+        sudo defaults write /Library/Preferences/com.apple.loginwindow RetriesUntilHint -int 0
+        echo "\t \t\033[00;32mDone\033[0m - Show password hints disabled"
+fi
+
+printf "\tDisable Allow guests to connect to shared folders [y/n] (y) ? "
+read guestshare
+if [ -z $guestshare ] || [ $guestshare == "y" ]
+then
+	sudo defaults write /Library/Preferences/com.apple.AppleFileServer guestAccess -bool no
+	echo "\t \t\033[00;32mDone\033[0m - Allow guests to connect to shared folders disabled"
+fi
+
+printf "\tSet a short inactivity interval for screen saver [y/n] (y) ? "
+read inacperiod
+if [ -z $inacperiod ] || [ $inacperiod == "y" ]
+then
+	printf "\t \tEnter inactivity interval period (<=900): "
+	read period 
+	sudo defaults -currentHost write com.apple.screensaver idleTime -int $period
+        echo "\t \t\033[00;32mDone\033[0m - Inactivity internal period set to $period"
+fi
+
 printf "\tSecure /usr/bin/dscl [y/n] (y) ? "
 read secdscl
 if [ -z $secdscl ] || [ $secdscl == "y" ]
 then
-	sudo chmod 100 /usr/bin/dscl
-	echo "\t \t\033[00;32mDone\033[0m - /usr/bin/dscl sets to 100"
+        sudo chmod 100 /usr/bin/dscl
+        echo "\t \t\033[00;32mDone\033[0m - /usr/bin/dscl sets to 100"
 fi
 
 printf "\tDisable Setuid and Setgid [y/n] (y) ? "
@@ -253,7 +348,7 @@ printf "\tFlush Directory Service cache [y/n] (y) ? "
 read dscache
 if [ -z $dscache ] || [ $dscache == "y" ]
 then
-	dscacheutil -flushcache
+	sudo dscacheutil -flushcache
 	echo "\t \t\033[00;32mDone\033[0m - Entire cache flushed"
 fi
 
@@ -265,12 +360,12 @@ then
 	then
 		if [ -z "$(grep "^export HISTTIMEFORMAT=\"\[%m.%d.%y\]@\[%T\] \"" /Users/$inuser/.profile)" ]
 		then
-			sed 's/^export HISTTIMEFORMAT.*$/export HISTTIMEFORMAT="[%m.%d.%y]@[%T] "/g' /Users/$inuser/.profile > /Users/$inuser/.profile.tmp
+			sudo sed 's/^export HISTTIMEFORMAT.*$/export HISTTIMEFORMAT="[%m.%d.%y]@[%T] "/g' /Users/$inuser/.profile > /Users/$inuser/.profile.tmp
 			cp /Users/$inuser/.profile.tmp /Users/$inuser/.profile
 			rm /Users/$inuser/.profile.tmp
 		fi
 	else
-		echo 'export HISTTIMEFORMAT="[%m.%d.%y]@[%T] "' >> /Users/$inuser/.profile
+		sudo echo 'export HISTTIMEFORMAT="[%m.%d.%y]@[%T] "' >> /Users/$inuser/.profile
 	fi
 	echo "\t \t\033[00;32mDone\033[0m - HISTTIMEFORMAT variable set in /Users/$inuser/.profile"
 fi 
@@ -285,12 +380,20 @@ then
 	/System/Library/QuickTime/QuickTimeUSBVDCDigitizer.component/Contents/MacOS/QuickTimeUSBVDCDigitizer
 	/System/Library/PrivateFrameworks/CoreMediaIOServicesPrivate.framework/Versions/A/Resources/VDC.plugin/Contents/MacOS/VDC
 	/System/Library/PrivateFrameworks/CoreMediaIOServices.framework/Versions/A/Resources/VDC.plugin/Contents/MacOS/VDC
-    )
+)
 	for d in
 	do
-        sudo /bin/chmod a-r $d 2>/dev/null
+        	sudo /bin/chmod a-r $d 2>/dev/null    
 	done
 	echo "\t \t\033[00;32mDone\033[0m - iSight camera disabled"
+fi
+
+printf "\tRemove iSight capabilities [y/n] (y) ? "
+read isightcap
+if [ -z $isightcap ] || [ $isightcap == "y" ]
+then
+        sudo rm -rf /System/Library/Extensions/Apple_iSight.kext
+	echo "\t \t\033[00;32mDone\033[0m - iSight capabilities removed"
 fi
 
 echo "\n[[System Utilities]]"
@@ -303,7 +406,7 @@ then
 	then
 		if [ -z "$(port 2>&1 | grep "command not found")" ] 
 		then
-			port install srm
+			sudo port install srm
 			alias rm=srm	
 			echo "\t \t\033[00;32mDone\033[0m - srm installed and rm alias to srm created"
 		else
@@ -313,10 +416,10 @@ then
 else
 	printf "\tSecure Remove (srm) is installed. Make alias to rm [y/n] (y) ? "
 	read secrm
-    if [ -z $secrm ] || [ $secrm == "y" ]
+        if [ -z $secrm ] || [ $secrm == "y" ]
 	then
 		alias rm=srm
-        echo "\t \t\033[00;32mDone\033[0m - rm alias to srm"	
+                echo "\t \t\033[00;32mDone\033[0m - rm alias to srm"	
 	fi
 fi
 
@@ -324,7 +427,7 @@ printf "\tEnable Finder secure remove [y/n] (y) ? "
 read findsrm
 if [ -z $findsrm ] || [ $findsrm == "y" ]
 then
-	defaults write com.apple.finder EmptyTrashSecurely -bool true
+	sudo defaults write com.apple.finder EmptyTrashSecurely -bool true
 	killall Finder
 	echo "\t \t\033[00;32mDone\033[0m - EmptyTrashSecurely on com.apple.finder sets to true"
 fi
@@ -334,12 +437,12 @@ read bktm
 if [ -z $bktm ] || [ $bktm == "y" ]
 then
 	if [ -f conf/com.apple.backup-auto.plist ]
-    then
+        then
 		sudo cp conf/com.apple.backupd-auto.plist /System/Library/LaunchDaemons/
-		sudo chown root:wheel /System/Library/LaunchDaemons/com.apple.backupd-auto.plist
-		sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.backupd-auto.plist > /dev/null 2>&1
+		chown root:wheel /System/Library/LaunchDaemons/com.apple.backupd-auto.plist
+		launchctl load -w /System/Library/LaunchDaemons/com.apple.backupd-auto.plist > /dev/null 2>&1
 		echo "\t \t\033[00;32mDone\033[0m - Updated StartInterval to 3600 on Daemon com.apple.backupd-auto"	
-		sudo launchctl start com.apple.backupd-auto
+		launchctl start com.apple.backupd-auto
 		echo "\t \t\033[00;32mDone\033[0m - Daemon com.apple.backupd-auto started"
 	fi
 fi
@@ -361,11 +464,21 @@ then
 	com.apple.webdavfs_load_kext
 	org.postfix.master
 	com.apple.efax
+        com.apple.AppleFileServer
+        org.apache.httpd
+        com.apple.InternetSharing
+        com.apple.mDNSResponder
+        com.apple.mDNSResponderHelper
+        eppc
+        ftp
+        nmbd
+        smbd
 	ssh)
 	for s in ${srvDaemons[@]}
 	do
-		launchctl unload -w /System/Library/LaunchDaemons/$s.plist	1>&2 2>/dev/null
+		sudo launchctl unload -w /System/Library/LaunchDaemons/$s.plist	1>&2 2>/dev/null
 	done
+
 
 	srvAgents=(
 	com.apple.RemoteDesktop 
@@ -373,7 +486,7 @@ then
 	)
 	for a in ${srvAgents[@]}
 	do
-		launchctl unload -w /System/Library/LaunchAgents/$a.plist 1>&2 2>/dev/null
+		sudo launchctl unload -w /System/Library/LaunchAgents/$a.plist 1>&2 2>/dev/null
 	done
 	echo "\t \t\033[00;32mDone\033[0m - Unnecessary Services disabled"
 fi
@@ -382,7 +495,7 @@ printf "\tDisable Remote Desktop [y/n] (y) ? "
 read remotedesk
 if [ -z $remotedesk ] || [ $remotedesk == "y" ] 
 then
-	/System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -deactivate -stop 2>/dev/null
+	sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -deactivate -stop 2>/dev/null
 	echo "\t \t\033[00;32mDone\033[0m - Remote Desktop disabled"
 fi
 
@@ -390,8 +503,8 @@ printf "\tDisable CUPS (Printer Sharing) [y/n] (y) ? "
 read cups
 if [ -z $cups ] || [ $cups == "y" ]
 then
-	launchctl unload -w /System/Library/LaunchDaemons/org.cups.cupsd.plist 1>&2 2>/dev/null
-    echo "\t \t\033[00;32mDone\033[0m - CUPS disabled"
+	sudo launchctl unload -w /System/Library/LaunchDaemons/org.cups.cupsd.plist 1>&2 2>/dev/null
+        echo "\t \t\033[00;32mDone\033[0m - CUPS disabled"
 fi
 
 printf "\tChange the global umask file permission [y/n] (y) ? "
@@ -405,8 +518,8 @@ then
 			if [ -z "$(grep "^umask 077" /etc/launchd.conf)" ]
 			then
 				sudo sed 's/umask.*$/umask\ 077/g' /etc/launchd.conf > /etc/launchd.conf.tmp
-				sudo cp /etc/launchd.conf.tmp /etc/launchd.conf
-				sudo rm /etc/launchd.conf.tmp
+				cp /etc/launchd.conf.tmp /etc/launchd.conf
+				rm /etc/launchd.conf.tmp
 			fi
 		else
 			sudo echo "umask 077" >> /etc/launchd.conf
@@ -424,17 +537,17 @@ printf "\tEnable OCSP Revocation to Best Attempt [y/n] (y) ? "
 read ocsp
 if [ -z $ocsp ] || [ $ocsp == "y" ]
 then
-	defaults write com.apple.security.revocation OCSPStyle -string BestAttempt
+	sudo defaults write com.apple.security.revocation OCSPStyle -string BestAttempt
 	echo "\t \t\033[00;32mDone\033[0m - Setting OCSPStyle com.apple.security.revocation to BestAttempt"
-    echo "\t \tDon't forget setting Priority to OCSP on Keychain Access > Preferences > Certificates tab"
+        echo "\t \tDon't forget setting Priority to OCSP on Keychain Access > Preferences > Certificates tab"
 fi
 
 printf "\tEnable CRL Revocation to Best Attempt [y/n] (y) ? "
 read crl
 if [ -z $crl ] || [ $crl == "y" ]
 then
-	defaults write com.apple.security.revocation CRLStyle -string BestAttempt
-    echo "\t \t\033[00;32mDone\033[0m - Setting CRLStyle com.apple.security.revocation to BestAttempt"
+	sudo defaults write com.apple.security.revocation CRLStyle -string BestAttempt
+        echo "\t \t\033[00;32mDone\033[0m - Setting CRLStyle com.apple.security.revocation to BestAttempt"
 fi
 
 echo "\n[[Manual Configuration]]"
